`timescale 1ns/1ps
`default_nettype none

// Parallel Wilkinson controller: one shared Gray-coded counter, one broadcast
// ramp, and one comparator per storage cell (IRSX-style conversion, adopted
// for Tape-out 1 on 2026-09-18 together with bottom-plate sampling).
//
// Sequence
//   IDLE    acquire=1  ramp_connect=0  ramp_reset=1   cells may track/hold
//   CONNECT acquire=0  ramp_connect=1  ramp_reset=1   bottom plates settle on
//                                                     the (reset) ramp output
//   CONVERT acquire=0  ramp_connect=1  ramp_reset=0   ramp runs, counter counts;
//                                                     every comparator falling
//                                                     edge captures the Gray word
//   DRAIN   counter overflowed; wait for late capture events to synchronize
//   -> done pulse, back to IDLE
//
// The bottom-plate switch order inside a cell (bottom switch opens before the
// top switch) is generated by the analog sampling sequencer; this controller
// only owns the acquire/convert mode and the ramp.
module parallel_wilkinson_controller #(
    parameter WIDTH = 8,
    parameter CELLS = 4,
    parameter CONNECT_CYCLES = 2,
    parameter DRAIN_CYCLES = 3
) (
    input  wire                   clk,
    input  wire                   rst_n,
    input  wire                   start,
    input  wire [CELLS-1:0]       compare_high,
    output reg                    acquire,
    output reg                    ramp_connect,
    output reg                    ramp_reset,
    output wire [CELLS*WIDTH-1:0] codes,
    output reg  [CELLS-1:0]       timeout,
    output reg                    busy,
    output reg                    done
);
    localparam IDLE    = 2'd0;
    localparam CONNECT = 2'd1;
    localparam CONVERT = 2'd2;
    localparam DRAIN   = 2'd3;

    reg [1:0]       state;
    reg [7:0]       wait_count;
    reg             converting;
    reg [WIDTH-1:0] binary_count;
    wire [WIDTH-1:0] gray_count = binary_count ^ (binary_count >> 1);

    reg [CELLS*WIDTH-1:0] code_r;
    reg [CELLS-1:0]       captured;
    assign codes = code_r;

    // ---- per-cell asynchronous Gray capture + toggle synchronizer ----------
    // Each channel's capture flops live inside its own generate block (one
    // clock per block) so lint tools see a single driver per register.
    wire [CELLS*WIDTH-1:0] captured_gray;
    wire [CELLS-1:0]       capture_toggle;
    reg  [CELLS-1:0] capture_sync1;
    reg  [CELLS-1:0] capture_sync2;
    reg  [CELLS-1:0] capture_seen;
    wire [CELLS-1:0] capture_event = capture_sync2 ^ capture_seen;

    genvar g;
    generate
        for (g = 0; g < CELLS; g = g + 1) begin : capture_channel
            reg [WIDTH-1:0] gray_q;
            reg             toggle_q;
            // The comparator edge is a local capture clock. Gray coding limits
            // a clock-boundary ambiguity to one counter bit (adjacent codes).
            always @(negedge compare_high[g] or negedge rst_n) begin
                if (!rst_n) begin
                    gray_q   <= {WIDTH{1'b0}};
                    toggle_q <= 1'b0;
                end else if (converting && !captured[g]) begin
                    gray_q   <= gray_count;
                    toggle_q <= ~toggle_q;
                end
            end
            assign captured_gray[g*WIDTH +: WIDTH] = gray_q;
            assign capture_toggle[g] = toggle_q;
        end
    endgenerate

    function [WIDTH-1:0] gray_to_binary;
        input [WIDTH-1:0] gray;
        integer k;
        begin
            gray_to_binary[WIDTH-1] = gray[WIDTH-1];
            for (k = WIDTH-2; k >= 0; k = k - 1)
                gray_to_binary[k] = gray_to_binary[k+1] ^ gray[k];
        end
    endfunction

    integer i;
    wire all_captured = &captured;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state         <= IDLE;
            wait_count    <= 8'd0;
            converting    <= 1'b0;
            binary_count  <= {WIDTH{1'b0}};
            code_r        <= {(CELLS*WIDTH){1'b0}};
            captured      <= {CELLS{1'b0}};
            timeout       <= {CELLS{1'b0}};
            capture_sync1 <= {CELLS{1'b0}};
            capture_sync2 <= {CELLS{1'b0}};
            capture_seen  <= {CELLS{1'b0}};
            acquire       <= 1'b1;
            ramp_connect  <= 1'b0;
            ramp_reset    <= 1'b1;
            busy          <= 1'b0;
            done          <= 1'b0;
        end else begin
            capture_sync1 <= capture_toggle;
            capture_sync2 <= capture_sync1;
            done <= 1'b0;

            // Accept synchronized capture events in any state; a late event
            // after overflow is still a valid code.
            for (i = 0; i < CELLS; i = i + 1) begin
                if (capture_event[i]) begin
                    capture_seen[i] <= capture_sync2[i];
                    if (converting && !captured[i]) begin
                        code_r[i*WIDTH +: WIDTH] <= gray_to_binary(captured_gray[i*WIDTH +: WIDTH]);
                        captured[i] <= 1'b1;
                    end
                end
            end

            case (state)
                IDLE: begin
                    acquire      <= 1'b1;
                    ramp_connect <= 1'b0;
                    ramp_reset   <= 1'b1;
                    busy         <= 1'b0;
                    converting   <= 1'b0;
                    if (start) begin
                        acquire      <= 1'b0;
                        ramp_connect <= 1'b1;
                        code_r       <= {(CELLS*WIDTH){1'b0}};
                        captured     <= {CELLS{1'b0}};
                        timeout      <= {CELLS{1'b0}};
                        capture_seen <= capture_sync2;
                        wait_count   <= CONNECT_CYCLES - 1;
                        busy         <= 1'b1;
                        state        <= CONNECT;
                    end
                end

                CONNECT: begin
                    if (wait_count == 0) begin
                        // Ramp released and counter started on the same edge.
                        ramp_reset   <= 1'b0;
                        binary_count <= {WIDTH{1'b0}};
                        converting   <= 1'b1;
                        state        <= CONVERT;
                    end else begin
                        wait_count <= wait_count - 1'b1;
                    end
                end

                CONVERT: begin
                    if (all_captured) begin
                        converting   <= 1'b0;
                        ramp_reset   <= 1'b1;
                        ramp_connect <= 1'b0;
                        acquire      <= 1'b1;
                        busy         <= 1'b0;
                        done         <= 1'b1;
                        state        <= IDLE;
                    end else if (&binary_count) begin
                        // Full scale reached: stop the ramp, keep accepting
                        // captures that are still in the synchronizer.
                        ramp_reset <= 1'b1;
                        wait_count <= DRAIN_CYCLES - 1;
                        state      <= DRAIN;
                    end else begin
                        binary_count <= binary_count + {{(WIDTH-1){1'b0}}, 1'b1};
                    end
                end

                DRAIN: begin
                    if (wait_count == 0 || all_captured) begin
                        for (i = 0; i < CELLS; i = i + 1) begin
                            if (!captured[i] && !capture_event[i]) begin
                                code_r[i*WIDTH +: WIDTH] <= {WIDTH{1'b1}};
                                timeout[i] <= 1'b1;
                            end
                        end
                        converting   <= 1'b0;
                        ramp_connect <= 1'b0;
                        acquire      <= 1'b1;
                        busy         <= 1'b0;
                        done         <= 1'b1;
                        state        <= IDLE;
                    end else begin
                        wait_count <= wait_count - 1'b1;
                    end
                end

                default: state <= IDLE;
            endcase
        end
    end
endmodule

`default_nettype wire
